%% ========================================================================
%  Intra-subject EMG Spectral Variability Analysis
%
%  Description:
%  ------------
%  This script quantifies intra-subject variability of EMG spectral
%  representations across repeated muscle activations.
%
%  The analysis is performed on preprocessed and normalized EMG spectra
%  (max-normalized or energy-normalized), previously obtained from:
%    - Biceps brachii
%    - Brachioradialis
%
%  and under two forearm postures:
%    - Supinated (SP)
%    - Neutral (NT)
%
%  For each subject and muscle-condition pair, the script:
%    1. Computes a mean EMG spectrum across repetitions
%    2. Measures the distance of each repetition to the mean spectrum
%    3. Extracts variability metrics (mean, std, CV)
%    4. Performs statistical comparison between postures (SP vs NT)
%    5. Visualizes variability using boxplots, histograms, and mean ± STD spectra
%
%  Distance metrics are computed in the spectral domain, providing a
%  frequency-based characterization of intra-subject EMG variability.
%
%  Author: Piotr Wawryka and Ludwin Molina Arias
%  Afiliation: AGH University of Krakow
% ========================================================================

clear; close all; clc;

%% ========================================================================
% 1. Configuration
% ========================================================================

nSubjects = 31;          % Total number of subjects
nSeg = 10;               % Number of repetitions per muscle
distType = 2;            % Distance metric: 1=L2, 2=L1, 3=Linf

normTypes = {'energy','max'};   % Perform both normalizations

muscleNames = {'BicepsBrachi_SP','BicepsBrachi_NT', ...
               'Brachioradialis_SP','Brachioradialis_NT'};
muscleLabels = {'BicepsBrachi SP','BicepsBrachi NT', ...
                'Brachioradialis SP','Brachioradialis NT'};
musclesToCompare = {'BicepsBrachi','Brachioradialis'};

%% ========================================================================
% 2. Load preprocessed EMG spectral data
% ========================================================================

% Data generated by the preprocessing pipeline
% Contains both max-normalized and energy-normalized spectra
load("Preprocessed_EMG.mat");

%% ========================================================================
% 3. Initialize data structures
% ========================================================================

Distances = struct();
Stats     = struct();
MeanSpectra = struct();

for normType = normTypes
    nt = normType{1};  % 'energy' o 'max'
    
    Distances.(nt) = struct();
    Stats.(nt) = struct();
    MeanSpectra.(nt) = struct();
    
    for iSubj = 1:nSubjects
        for m = 1:4
            Distances.(nt)(iSubj).(muscleNames{m}).Euclidean = [];
            Stats.(nt)(iSubj).(muscleNames{m}) = struct('mean',0,'std',0,'cv',0,'stdSpectrum',[]);
            MeanSpectra.(nt)(iSubj).(muscleNames{m}) = [];
        end
    end
end

%% ========================================================================
% 4. Compute distances, statistics, and mean spectra for both normalizations
% ========================================================================

for iSubj = 1:nSubjects
    fieldName = sprintf('subject%02d', iSubj);

    for n = 1:numel(normTypes)
        normType = normTypes{n};  % 'energy' o 'max'

        % Select normalization-specific muscle data
        switch normType
            case 'energy'
                musclesData = {BicepsBrachi_SP_energy.(fieldName), ...
                               BicepsBrachi_NT_energy.(fieldName), ...
                               Brachioradialis_SP_energy.(fieldName), ...
                               Brachioradialis_NT_energy.(fieldName)};
            case 'max'
                musclesData = {BicepsBrachi_SP_max.(fieldName), ...
                               BicepsBrachi_NT_max.(fieldName), ...
                               Brachioradialis_SP_max.(fieldName), ...
                               Brachioradialis_NT_max.(fieldName)};
        end

        % Loop over muscles
        for m = 1:4
            segs = musclesData{m};
            nS = numel(segs);

            % Build spectral matrix (columns = repetitions)
            spectraMat = zeros(length(segs(1).smoothSpectrum), nS);
            for j = 1:nS
                spectraMat(:,j) = segs(j).smoothSpectrum(:);
            end

            % Mean and STD spectrum
            meanSpectrum = mean(spectraMat, 2);
            stdSpectrum  = std(spectraMat, 0, 2);

            % Store mean spectrum and STD
            MeanSpectra.(normType)(iSubj).(muscleNames{m}) = meanSpectrum;
            Stats.(normType)(iSubj).(muscleNames{m}).stdSpectrum = stdSpectrum;

            % Compute distance of each repetition to the mean spectrum
            dE = zeros(1, nS);
            for j = 1:nS
                switch distType
                    case 1
                        dE(j) = norm(spectraMat(:,j) - meanSpectrum, 2); % Euclidean
                    case 2
                        dE(j) = norm(spectraMat(:,j) - meanSpectrum, 1); % Manhattan
                    case 3
                        dE(j) = norm(spectraMat(:,j) - meanSpectrum, Inf); % Chebyshev
                end
            end

            % Store distance statistics
            Stats.(normType)(iSubj).(muscleNames{m}).mean = mean(dE);
            Stats.(normType)(iSubj).(muscleNames{m}).std  = std(dE);
            Stats.(normType)(iSubj).(muscleNames{m}).cv   = std(dE)/mean(dE);
            Distances.(normType)(iSubj).(muscleNames{m}).Euclidean = dE;
        end
    end
end

%% ========================================================================
% 5. Save distance and statistics data for both normalizations
% ========================================================================

% Create results folder if it does not exist
if ~exist('Results','dir')
    mkdir('Results');
end

% Save structures into separate files
DistancesEnergy = Distances.energy;
DistancesMax    = Distances.max;
StatsEnergy     = Stats.energy;
StatsMax        = Stats.max;
MeanSpectraEnergy = MeanSpectra.energy;
MeanSpectraMax    = MeanSpectra.max;

save(fullfile('Results','Distances_Energy.mat'), 'DistancesEnergy', 'StatsEnergy', 'MeanSpectraEnergy');
save(fullfile('Results','Distances_Max.mat'),    'DistancesMax',    'StatsMax',    'MeanSpectraMax');

disp('Intra-subject distances and statistics saved for both normalizations (energy & max).');

%% ========================================================================
% 6. Statistical table of intra-subject variability for both normalizations
% ========================================================================

% Define normalizations to iterate over
normTypes = {'energy','max'};

% Initialize final results table
resultsTable = table( ...
    'Size',[numel(normTypes)*4 7], ... % 4 conditions per normalization
    'VariableTypes',{'string','string','double','double','double','double','double'}, ...
    'VariableNames',{'Muscle','Condition','Mean','STD','CV','Min','Max'});

row = 1;

for n = 1:numel(normTypes)
    normType = normTypes{n};
    
    for m = 1:2 % 1=Biceps, 2=Brachioradialis
        
        switch m
            case 1
                spField = 'BicepsBrachi_SP';
                ntField = 'BicepsBrachi_NT';
                muscle  = 'Biceps brachii';
            case 2
                spField = 'Brachioradialis_SP';
                ntField = 'Brachioradialis_NT';
                muscle  = 'Brachioradialis';
        end
        
        for cond = ["SP","NT"]
            
            vals = zeros(nSubjects,1);
            
            for iSubj = 1:nSubjects
                % Select stats structure according to normalization
                if strcmp(normType,'energy')
                    statsStruct = StatsEnergy;
                else
                    statsStruct = StatsMax;
                end
                
                if cond == "SP"
                    vals(iSubj) = statsStruct(iSubj).(spField).mean;
                else
                    vals(iSubj) = statsStruct(iSubj).(ntField).mean;
                end
            end
            
            % Fill results table
            resultsTable.Muscle{row}     = muscle;
            resultsTable.Condition{row}  = char(cond);
            resultsTable.Mean(row)       = mean(vals);
            resultsTable.STD(row)        = std(vals);
            resultsTable.CV(row)         = std(vals)/mean(vals);
            resultsTable.Min(row)        = min(vals);
            resultsTable.Max(row)        = max(vals);
            
            row = row + 1;
        end
    end
end

disp('Intra-subject variability table (Energy & Max) computed:');
disp(resultsTable);

%% ========================================================================
% 7. Global boxplot of intra-subject EMG spectral variability (Energy & Max)
% ========================================================================
%
% This section visualizes intra-subject spectral variability for all muscles
% and postures using boxplots. Each normalization type (Energy, Max) is
% displayed in a separate subplot within a single figure.
%
% Purpose:
%   - Compare variability across muscles and postures
%   - Show differences between normalization methods
%
% Subplots:
%   - Left: Max-normalized data
%   - Right: Energy-normalized data
%

normTypes = {'max','energy'};  % Order for subplot arrangement

figure('Name','Intra-subject variability (Max & Energy)','NumberTitle','off','Color','w');

% Custom colors (Nature-style)
boxColors = [0 0 0.7;        % dark blue for Max
             0.85 0.33 0.1]; % orange for Energy

for n = 1:numel(normTypes)
    
    normType = normTypes{n};
    
    % Initialize data and labels containers
    data = [];
    labels = {};
    
    for m = 1:2  % 1=Biceps, 2=Brachioradialis
        switch m
            case 1
                spField = 'BicepsBrachi_SP';
                ntField = 'BicepsBrachi_NT';
                muscleLabel = 'BB';
            case 2
                spField = 'Brachioradialis_SP';
                ntField = 'Brachioradialis_NT';
                muscleLabel = 'BR';
        end
        
        for cond = ["SP","NT"]
            vals = zeros(nSubjects,1);
            
            for iSubj = 1:nSubjects
                % Select stats structure according to normalization
                if strcmp(normType,'energy')
                    statsStruct = StatsEnergy;
                    col = 2; % orange
                else
                    statsStruct = StatsMax;
                    col = 1; % blue
                end
                
                if cond == "SP"
                    vals(iSubj) = statsStruct(iSubj).(spField).mean;
                else
                    vals(iSubj) = statsStruct(iSubj).(ntField).mean;
                end
            end
            
            % Append values and labels
            data   = [data; vals];
            labels = [labels; repmat({[muscleLabel '/' char(cond)]}, nSubjects, 1)];
        end
    end
    
    % Create subplot for this normalization
    subplot(1,2,n)
    
    % Boxplot
    h = boxplot(data, labels, ...
                'Whisker',1.5, ...
                'Symbol','o', ...
                'MedianStyle','line', ...
                'Widths',0.5);
    
    % Color boxes
    boxes = findobj(gca,'Tag','Box'); boxes = flipud(boxes);
    for k = 1:length(boxes)
        patch(get(boxes(k),'XData'), get(boxes(k),'YData'), ...
              boxColors(col,:), 'FaceAlpha',0.3, 'EdgeColor',boxColors(col,:), 'LineWidth',1.2);
    end
    
    % Whiskers
    whiskers = findobj(gca,'Tag','Whisker'); whiskers = flipud(whiskers);
    set(whiskers,'Color','k','LineWidth',1.5);
    
    % Caps
    caps = findobj(gca,'Tag','Upper Whisker'); caps = flipud(caps);
    for k = 1:length(caps), set(caps(k),'Color','k','LineWidth',1.5); end
    caps = findobj(gca,'Tag','Lower Whisker'); caps = flipud(caps);
    for k = 1:length(caps), set(caps(k),'Color','k','LineWidth',1.5); end
    
    % Medians
    set(findobj(gca,'Tag','Median'),'Color','k','LineWidth',1.8);
    
    % Outliers
    outliers = findobj(gca,'Tag','Outliers'); set(outliers,'Color','k','MarkerSize',7);
    
    % Axes and formatting
    ylabel('Mean spectral distance (a.u.)','FontSize',12,'FontWeight','bold');
    xlabel('Muscle/Posture','FontSize',12,'FontWeight','bold');
    grid on;
    ax = gca; ax.FontSize = 12; ax.LineWidth = 1; ax.Box = 'off';
end

% Save the combined figure
FigArticle('IntraSubj_Boxplots','vector',14);

%% ========================================================================
% 8. Statistical testing (Wilcoxon signed-rank) for Energy & Max
% ========================================================================

normTypes = {'energy','max'};  % iterar sobre ambas normalizaciones

for n = 1:numel(normTypes)
    
    normType = normTypes{n};
    fprintf('\n=== Normalization: %s ===\n', normType);
    
    for m = 1:2  % 1=Biceps, 2=Brachioradialis
        switch m
            case 1
                spField = 'BicepsBrachi_SP';
                ntField = 'BicepsBrachi_NT';
                muscle  = 'Biceps brachii';
            case 2
                spField = 'Brachioradialis_SP';
                ntField = 'Brachioradialis_NT';
                muscle  = 'Brachioradialis';
        end
        
        spVals = zeros(nSubjects,1);
        ntVals = zeros(nSubjects,1);
        
        for iSubj = 1:nSubjects
            if strcmp(normType,'energy')
                statsStruct = StatsEnergy;
            else
                statsStruct = StatsMax;
            end
            
            spVals(iSubj) = statsStruct(iSubj).(spField).mean;
            ntVals(iSubj) = statsStruct(iSubj).(ntField).mean;
        end
        
        % Wilcoxon signed-rank test
        [p,~,statsTest] = signrank(spVals, ntVals);
        
        fprintf('%s | Wilcoxon SP vs NT: p = %.4f (W = %.2f)\n', muscle, p, statsTest.signedrank);
        
        % Interpretación automática
        if p < 0.05
            fprintf('  → Statistically significant difference between postures (SP vs NT)\n');
        else
            fprintf('  → No statistically significant difference between postures\n');
        end
    end
end

%% ========================================================================
% 9. Mean spectrum ± STD visualization (Energy & Max)
% ========================================================================

normTypes = {'energy','max'};  % Iterate over both normalizations
muscleData = {'BicepsBrachi_SP','BicepsBrachi_NT','Brachioradialis_SP','Brachioradialis_NT'};
subplotLetters = {'(a)','(b)','(c)','(d)'};

% Define single color per normalization
colorEnergy = [0.85 0.33 0.1]; % orange
colorMax    = [0 0.4470 0.7410]; % blue

iSubj = 1; % Subject to visualize (can be changed)

for n = 1:numel(normTypes)
    
    normType = normTypes{n};
    fig = figure('Name',sprintf('Mean Spectrum ± STD (%s)',normType), ...
                 'NumberTitle','off','Color','w');
    
    % Select color for this normalization
    if strcmp(normType,'energy')
        currColor = colorEnergy;
    else
        currColor = colorMax;
    end
    
    for m = 1:4
        subplot(2,2,m)
        muscle = muscleData{m};
        
        % Select data according to normalization
        if strcmp(normType,'energy')
            meanSpec = MeanSpectraEnergy(iSubj).(muscle);
            stdSpec  = StatsEnergy(iSubj).(muscle).stdSpectrum;
            segs     = eval([muscle '_energy']);  % frequency vector
        else
            meanSpec = MeanSpectraMax(iSubj).(muscle);
            stdSpec  = StatsMax(iSubj).(muscle).stdSpectrum;
            segs     = eval([muscle '_max']);  % frequency vector
        end
        
        freq = segs(1).(sprintf('subject%02d',iSubj)).frequency;
        
        % Shaded ±1 STD
        fill([freq; flipud(freq)], [meanSpec+stdSpec; flipud(meanSpec-stdSpec)], ...
             currColor, 'FaceAlpha',0.2, 'EdgeColor','none'); hold on;
        
        % Mean line
        plot(freq, meanSpec, 'Color', currColor, 'LineWidth',2); hold off;
        
        % Axis labels and formatting
        xlabel('Frequency (Hz)','FontSize',12,'FontWeight','bold')
        ylabel('Normalized PSD (a.u.)','FontSize',12,'FontWeight','bold')
        xlim([0 200])
        if strcmp(normType,'energy')
            ylim([0 0.045])
        else
            ylim([0 1])
        end
        box off
        set(gca,'FontSize',12,'LineWidth',1,'TickDir','out')
        title(subplotLetters{m})
    end
    
    % Save figure according to normalization
    if strcmp(normType,'energy')
        FigArticle('Energy_Mean_Spectrum','vector',14)
    else
        FigArticle('Max_Mean_Spectrum','vector',14)
    end
end

%% ========================================================================
% 10. Data-driven conclusions (Energy & Max)
% ========================================================================

normTypes = {'energy','max'};

fprintf('\n====================================================\n');
fprintf('INTRA-SUBJECT EMG SPECTRAL VARIABILITY – CONCLUSIONS\n');

for n = 1:numel(normTypes)
    
    normalizationType = normTypes{n};
    fprintf('Normalization: %s\n', normalizationType);
    fprintf('Distance metric: %d (1=L2, 2=L1, 3=L∞)\n', distType);
    fprintf('====================================================\n\n');
    
    % Select the corresponding stats structure
    if strcmp(normalizationType,'energy')
        statsStruct = StatsEnergy;
    else
        statsStruct = StatsMax;
    end
    
    for i = 1:length(musclesToCompare)
        muscle = musclesToCompare{i};
        
        % Extract intra-subject mean distances for SP and NT
        SP_vals = arrayfun(@(s) s.([muscle '_SP']).mean, statsStruct);
        NT_vals = arrayfun(@(s) s.([muscle '_NT']).mean, statsStruct);
        
        % Descriptive statistics
        SP_mean = mean(SP_vals);
        NT_mean = mean(NT_vals);
        SP_std  = std(SP_vals);
        NT_std  = std(NT_vals);
        SP_cv   = SP_std / SP_mean;
        NT_cv   = NT_std / NT_mean;
        
        % Wilcoxon signed-rank test SP vs NT
        [p,~,statsTest] = signrank(SP_vals, NT_vals);
        
        % Print results
        fprintf('Muscle: %s\n', muscle);
        fprintf('  SP: Mean = %.4f | STD = %.4f | CV = %.3f\n', SP_mean, SP_std, SP_cv);
        fprintf('  NT: Mean = %.4f | STD = %.4f | CV = %.3f\n', NT_mean, NT_std, NT_cv);
        fprintf('  Wilcoxon signed-rank: p = %.4f (W = %.2f)\n', p, statsTest.signedrank);
        
        % Automatic interpretation
        if p < 0.05
            fprintf('  → Statistically significant difference between postures (SP vs NT).\n');
        else
            fprintf('  → No statistically significant difference between postures.\n');
        end
        
        if SP_mean > NT_mean
            fprintf('  → Higher intra-subject spectral variability in SP condition.\n');
        elseif NT_mean > SP_mean
            fprintf('  → Higher intra-subject spectral variability in NT condition.\n');
        else
            fprintf('  → Comparable intra-subject variability across postures.\n');
        end
        
        fprintf('\n');
    end
    
    fprintf('====================================================\n\n');
end

